### ISSUE TITLE
HOME button doesn't always work from Guide

### ISSUE THREAD

**Issue by Skirge01** [sagecollegeproject/SageCollegeProject#25]
If you begin watching a show from the Guide and then stop playback, HOME will not bring you back to the main menu.  If you hit HOME twice, then it will.  This happens if you're on the guide when playback stops or if the slideout menu (containing WatchNow) is on the screen.

**Comment by sagecollegeproject** [comment]
Added listeners to build 1.25.1 this should fix this issues
