### ISSUE TITLE
Favorites Missing

### ISSUE THREAD

**Issue by Skirge01** [sagecollegeproject/SageCollegeProject#4]
ManageFavorites only shows favorites for which there is an airing within the upcoming recording window (usually the next 7 days).  If no airings are in the guide or the airing is beyond the recording window, the favorite is not shown.

**Comment by sagecollegeproject** [comment]
Issue fixed in upcoming build. Required STV fixes and new VFS.xml
If VFS is custom please backup first. 
SageCollegeProject_PublicBeta_1.19_1_FixFavorites_Github
APi build 1.31
