### ISSUE TITLE
Support SELECT/OK & PLAY for playback/options

### ISSUE THREAD

**Issue by Skirge01** [sagecollegeproject/SageCollegeProject#6]
Add ability to choose whether "select/ok" or "play" accomplishes one of the following:

* Begin playback
* Display options menu for playback (resume, delete, etc)

...with the other button doing the opposite.

**Comment by sagecollegeproject** [comment]
Ctrl+D or Play is now instant (or asks to resume) no submenu loaded.

SageCollegeProject_PublicBeta_1.19_2_PlayIsInstant_Github
